# Generated by Django 5.2.7 on 2025-10-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_author_alter_blog_options_rename_text_blog_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='editorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='authentication.blog')),
            ],
        ),
    ]
